/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorpro;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian
 */
public class Window extends javax.swing.JFrame {

    PassVerifier verifier = new PassVerifier();
    private boolean flag1 = false;
    private boolean flag2 = false;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        actionSymbol.setModel(new DefaultComboBoxModel(ActionSymbol.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtField1 = new javax.swing.JFormattedTextField();
        actionSymbol = new javax.swing.JComboBox();
        txtField2 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtFieldResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator 1.2v");
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Wartości"));
        jPanel1.setFocusCycleRoot(true);

        txtField1.setPreferredSize(new java.awt.Dimension(100, 35));
        txtField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtField1KeyReleased(evt);
            }
        });
        jPanel1.add(txtField1);

        jPanel1.add(actionSymbol);

        txtField2.setToolTipText("");
        txtField2.setPreferredSize(new java.awt.Dimension(100, 35));
        txtField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtField2KeyReleased(evt);
            }
        });
        jPanel1.add(txtField2);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Funkcje"));

        jButton1.setText("Oblicz");
        jButton1.setEnabled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Wynik"));

        txtFieldResult.setPreferredSize(new java.awt.Dimension(120, 35));
        jPanel3.add(txtFieldResult);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField1KeyReleased
        
        flag1 = verifier.verify(txtField1);
        if(flag1) {
            txtField1.setBackground(Color.green);
        } else {
            txtField1.setBackground(Color.red);
        }
        check();
    }//GEN-LAST:event_txtField1KeyReleased

    private void txtField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtField2KeyReleased
        
        flag2 = verifier.verify(txtField2);
        if(flag2) {
            txtField2.setBackground(Color.green);
        } else {
            txtField2.setBackground(Color.red);
        }
        check();
    }//GEN-LAST:event_txtField2KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        double number1 = Double.parseDouble(txtField1.getText());
        double number2 = Double.parseDouble(txtField2.getText());
        
        if(check()) {
           if((number1 >= -30000 && number2 >= -30000) && ((number1 <= 30000 && number2 <= 30000))) {
               
                double result = 0; 
                
                switch ((ActionSymbol)actionSymbol.getSelectedItem()) {
                    case ADD:
                        result = number1 + number2;
                        break;
                    case SUBTRACT:
                        result = number1 - number2;
                        break;
                    case MULTIPLY:
                        result = number1 * number2;
                        break;
                    case DIVIDE:
                        if(number2 != 0) {
                            result = number1 / number2;
                        } else {
                            JOptionPane.showMessageDialog(null, "Nie można dzielić przez zero!");
                        }
                        break;
                }
                
                txtFieldResult.setText(String.valueOf(result));
             
           } else {
               JOptionPane.showMessageDialog(null, "Wprowadzona liczba wychodzi poza zakres!");
           }         
        } else {
            JOptionPane.showMessageDialog(null, "Wprowadzono nieprawidłową wartość!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean check() {
        if ((flag1 && flag2) == true) {
            jButton1.setEnabled(true);
            return true;
        } else {
            jButton1.setEnabled(false);
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Window().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionSymbol;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField txtField1;
    private javax.swing.JFormattedTextField txtField2;
    private javax.swing.JTextField txtFieldResult;
    // End of variables declaration//GEN-END:variables
}
